del  .\HW.Api\bin\*.*   /s /q
del  .\HW.Api\obj\*.*   /s /q
del  .\HW.Api\wwwroot\ui\*.*   /s /q
del  .\HW.Api\WMBlog.db   /s /q
del  .\HW.Common\bin\*.*   /s /q
del  .\HW.Common\obj\*.*   /s /q
del  .\HW.EventBus\bin\*.*   /s /q
del  .\HW.EventBus\obj\*.*   /s /q
del  .\HW.Extensions\bin\*.*   /s /q
del  .\HW.FrameWork\bin\*.*   /s /q
del  .\HW.Gateway\bin\*.*   /s /q
del  .\HW.IServices\bin\*.*   /s /q
del  .\HW.Model\bin\*.*   /s /q
del  .\HW.Repository\bin\*.*   /s /q
del  .\HW.Serilog.Es\bin\*.*   /s /q
del  .\HW.Services\bin\*.*   /s /q
del  .\HW.Tasks\bin\*.*   /s /q
del  .\HW.Tests\bin\*.*   /s /q
del  .\Ocelot.Provider.Nacos\bin\*.*   /s /q

del  .\HW.Extensions\obj\*.*   /s /q
del  .\HW.FrameWork\obj\*.*   /s /q
del  .\HW.Gateway\obj\*.*   /s /q
del  .\HW.IServices\obj\*.*   /s /q
del  .\HW.Model\obj\*.*   /s /q
del  .\HW.Repository\obj\*.*   /s /q
del  .\HW.Serilog.Es\obj\*.*   /s /q
del  .\HW.Services\obj\*.*   /s /q
del  .\HW.Tasks\obj\*.*   /s /q
del  .\HW.Tests\obj\*.*   /s /q
del  .\Ocelot.Provider.Nacos\obj\*.*   /s /q